services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kinobot
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - .env:/bot/.env
    command: ["python", "./main.py"]
    networks:
      - redis

  redis:
    image: redis:7.2-alpine
    container_name: redis_cache
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env
    ports:
      - "7379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - redis

volumes:
  redis_data:

networks:
  redis:
    driver: bridge
